/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.PilaBits;
import Negocio.PilaLista;
import Negocio.PilaV;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class PilaFormulario extends javax.swing.JFrame {

    PilaV PVector;
    PilaBits PBits;
    PilaLista PLista;
    Boolean BotonBits = false;
    Boolean BotonNBits = false;

    /**
     * Creates new form PilaFormulario
     */
    public PilaFormulario() {
        initComponents();
        PLista = new PilaLista();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PushVector = new javax.swing.JButton();
        ElementoVector = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaVector = new javax.swing.JTextArea();
        TamañoVector = new javax.swing.JButton();
        ETVector = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PopVector = new javax.swing.JButton();
        GetVector = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PushBits = new javax.swing.JButton();
        ElementoBits = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaBits = new javax.swing.JTextArea();
        GenerarBits = new javax.swing.JButton();
        NBits = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ETBits = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PopBits = new javax.swing.JButton();
        GetBits = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PushLista = new javax.swing.JButton();
        ElementoLista = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        AreaLista = new javax.swing.JTextArea();
        PopLista = new javax.swing.JButton();
        GetLista = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Pila Vector", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Elemento:");

        PushVector.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PushVector.setText("Push");
        PushVector.setEnabled(false);
        PushVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PushVectorActionPerformed(evt);
            }
        });

        ElementoVector.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ElementoVector.setEnabled(false);
        ElementoVector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ElementoVectorKeyReleased(evt);
            }
        });

        AreaVector.setEditable(false);
        AreaVector.setColumns(20);
        AreaVector.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        AreaVector.setRows(5);
        jScrollPane1.setViewportView(AreaVector);

        TamañoVector.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TamañoVector.setText("Generar");
        TamañoVector.setEnabled(false);
        TamañoVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TamañoVectorActionPerformed(evt);
            }
        });

        ETVector.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ETVector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ETVectorKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Tamaño:");

        PopVector.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PopVector.setText("Pop");
        PopVector.setEnabled(false);
        PopVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopVectorActionPerformed(evt);
            }
        });

        GetVector.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        GetVector.setText("Get");
        GetVector.setEnabled(false);
        GetVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetVectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ETVector)
                    .addComponent(ElementoVector, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TamañoVector)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PushVector)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PopVector, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(GetVector, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TamañoVector)
                    .addComponent(ETVector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PushVector)
                    .addComponent(ElementoVector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopVector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GetVector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Pila Bits", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Elemento:");

        PushBits.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PushBits.setText("Push");
        PushBits.setEnabled(false);
        PushBits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PushBitsActionPerformed(evt);
            }
        });

        ElementoBits.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ElementoBits.setEnabled(false);
        ElementoBits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ElementoBitsKeyReleased(evt);
            }
        });

        AreaBits.setEditable(false);
        AreaBits.setColumns(20);
        AreaBits.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        AreaBits.setRows(5);
        jScrollPane2.setViewportView(AreaBits);

        GenerarBits.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        GenerarBits.setText("Generar");
        GenerarBits.setEnabled(false);
        GenerarBits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarBitsActionPerformed(evt);
            }
        });

        NBits.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NBits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NBitsKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Tamaño:");

        ETBits.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ETBits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ETBitsKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Bits:");

        PopBits.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PopBits.setText("Pop");
        PopBits.setEnabled(false);
        PopBits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopBitsActionPerformed(evt);
            }
        });

        GetBits.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        GetBits.setText("Get");
        GetBits.setEnabled(false);
        GetBits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetBitsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ElementoBits, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PushBits)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PopBits)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GetBits))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ETBits, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(NBits, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GenerarBits)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ETBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenerarBits)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PushBits)
                    .addComponent(ElementoBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopBits)
                    .addComponent(GetBits))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Pila Lista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Elemento:");

        PushLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PushLista.setText("Push");
        PushLista.setEnabled(false);
        PushLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PushListaActionPerformed(evt);
            }
        });

        ElementoLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ElementoLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ElementoListaKeyReleased(evt);
            }
        });

        AreaLista.setEditable(false);
        AreaLista.setColumns(20);
        AreaLista.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        AreaLista.setRows(5);
        jScrollPane3.setViewportView(AreaLista);

        PopLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PopLista.setText("Pop");
        PopLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopListaActionPerformed(evt);
            }
        });

        GetLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        GetLista.setText("Get");
        GetLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(ElementoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PushLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GetLista)
                            .addComponent(PopLista))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PushLista)
                    .addComponent(ElementoLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GetLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pilas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PushListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PushListaActionPerformed

        int x = Integer.valueOf(ElementoLista.getText());
        PLista.Push(x);
        AreaLista.setText(PLista.toString());
        ElementoLista.setText("");
        PushLista.setEnabled(false);
    }//GEN-LAST:event_PushListaActionPerformed
    private boolean EsNumero(String Valor) {
        return Valor.matches("[0-9]*");

    }
    private void TamañoVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TamañoVectorActionPerformed

        int x = Integer.valueOf(ETVector.getText());
        PVector = new PilaV(x);
        TamañoVector.setEnabled(false);
        //ETVector.setEnabled(false);
        //PushVector.setEnabled(true);
        ElementoVector.setEnabled(true);
        PopVector.setEnabled(true);
        AreaVector.setText("");
        GetVector.setEnabled(true);
    }//GEN-LAST:event_TamañoVectorActionPerformed

    private void ETVectorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ETVectorKeyReleased
        if (EsNumero(ETVector.getText()) && ETVector.getText().length() != 0 && Integer.valueOf(ETVector.getText()) > 0) {
            TamañoVector.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(rootPane, "Elemento Invalido", "Estructura de Datos 1",1);
            TamañoVector.setEnabled(false);
            ETVector.setText("");
        }
    }//GEN-LAST:event_ETVectorKeyReleased
    private void ValidarPush(String Valor, JButton Tamaño, JTextField Texto) {
        //JOptionPane.showMessageDialog(rootPane, );
        if (Valor.length() != 0) {
            //&& Integer.valueOf(Valor) > 0) {

            Tamaño.setEnabled(true);
        } else {
            //JOptionPane.showMessageDialog(rootPane, "Elemento Invalido", "Estructura de Datos 1",1);
            Tamaño.setEnabled(false);
            //Texto.setText("");
        }

    }
    private void ElementoVectorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ElementoVectorKeyReleased
        ValidarPush(ElementoVector.getText(), PushVector, ElementoVector);
    }//GEN-LAST:event_ElementoVectorKeyReleased

    private void PushVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PushVectorActionPerformed
        if (!PVector.Llena()) {
            int x = Integer.valueOf(ElementoVector.getText());
            PVector.Push(x);
            AreaVector.setText(PVector.toString());
            ElementoVector.setText("");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Pila Llena","Estructura de Datos 1",1);
            ElementoVector.setText("");

        }
        PushVector.setEnabled(false);
    }//GEN-LAST:event_PushVectorActionPerformed
    private void HabilitarBits() {
        if (BotonNBits && BotonBits) {
            GenerarBits.setEnabled(true);
        } else {
            GenerarBits.setEnabled(false);
        }
        /*if (ETBits.getText().length() != 0 && NBits.getText().length() != 0) {
            int nbit = Integer.valueOf(ETBits.getText());
            int cant = Integer.valueOf(NBits.getText());
            if (!ETBits.getText().matches("[0-9*") || !NBits.getText().matches("[0-9*")) {
                ETBits.setText("");
                NBits.setText("");
                GenerarBits.setEnabled(false);
            } else {
                if (nbit != 0 && cant != 0) {
                    GenerarBits.setEnabled(true);
                } else {
                    ETBits.setText("");
                    NBits.setText("");
                    GenerarBits.setEnabled(false);
                }
            }
        }*/
    }
    private void ETBitsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ETBitsKeyReleased
        if (ETBits.getText().matches("[0-9]*") && (ETBits.getText().length() != 0)) {
            if (Integer.valueOf(ETBits.getText()) != 0) {
                BotonBits = true;
            } else {
                BotonBits = false;
            }

        } else {
            BotonBits = false;
            ETBits.setText("");
        }
        HabilitarBits();
    }//GEN-LAST:event_ETBitsKeyReleased

    private void NBitsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NBitsKeyReleased
        if (NBits.getText().matches("[0-9]*") && (NBits.getText().length() != 0)) {
            if (Integer.valueOf(NBits.getText()) != 0) {
                BotonNBits = true;
            } else {
                BotonNBits = false;
            }

        } else {
            BotonNBits = false;
            NBits.setText("");
        }
        HabilitarBits();
    }//GEN-LAST:event_NBitsKeyReleased

    private void GenerarBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarBitsActionPerformed
        int cant = Integer.valueOf(ETBits.getText());
        int nbit = Integer.valueOf(NBits.getText());
        PBits = new PilaBits(cant, nbit);
        AreaBits.setText("");
        GenerarBits.setEnabled(false);
        ElementoBits.setEnabled(true);
        PopBits.setEnabled(true);
        GetBits.setEnabled(true);
    }//GEN-LAST:event_GenerarBitsActionPerformed

    private void ElementoBitsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ElementoBitsKeyReleased
        if(ElementoBits.getText().matches("[0-9]*")){
        ValidarPush(ElementoBits.getText(), PushBits, ElementoBits);
        }
    }//GEN-LAST:event_ElementoBitsKeyReleased

    private void PushBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PushBitsActionPerformed
        int x = Integer.valueOf(ElementoBits.getText());
        if (!PBits.Llena()&& x<Math.pow(2,PBits.Nbit())) {  
            PBits.Push(x);
            AreaBits.setText(PBits.toString());
            ElementoBits.setText("");
        } else {
            if(x>=Math.pow(2,PBits.Nbit())){
                int y = (int) (Math.pow(2, PBits.Nbit()) -1);
                JOptionPane.showMessageDialog(rootPane, "El Valor MAXIMO debe ser de " + y, "Estructura de Datos 1", 1);
            }
            else
            JOptionPane.showMessageDialog(rootPane, "Pila Llena", "Estructura de Datos 1", 1);
  ElementoBits.setText("");
        }
        PushBits.setEnabled(false);
    }//GEN-LAST:event_PushBitsActionPerformed

    private void PopVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopVectorActionPerformed
        if (!PVector.Vacia()) {
            int x = PVector.Pop();
            JOptionPane.showMessageDialog(rootPane, "Elemento: " + x,"Pop",1);
            AreaVector.setText(PVector.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "La Pila no tiene Elementos","Estructura de Datos 1",1);
        }

    }//GEN-LAST:event_PopVectorActionPerformed

    private void PopBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopBitsActionPerformed
        if (!PBits.Vacia()) {
            int x = PBits.Pop();
            JOptionPane.showMessageDialog(rootPane, "Elemento: " + x,"Pop",1);
            AreaBits.setText(PBits.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "La Pila no tiene Elementos","Estructura de Datos 1",1);
        }
    }//GEN-LAST:event_PopBitsActionPerformed

    private void PopListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopListaActionPerformed
        if (!PLista.Vacia()) {
            int x = PLista.Pop();
            JOptionPane.showMessageDialog(rootPane, "Elemento: " + x,"Pop",1);
            AreaLista.setText(PLista.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "La Pila no tiene Elementos","Estructura de Datos 1",1);
        }
    }//GEN-LAST:event_PopListaActionPerformed

    private void ElementoListaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ElementoListaKeyReleased
        ValidarPush(ElementoLista.getText(), PushLista, ElementoLista);
    }//GEN-LAST:event_ElementoListaKeyReleased

    private void GetVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetVectorActionPerformed
        if (!PVector.Vacia()) {
            int x = PVector.Get();
            JOptionPane.showMessageDialog(rootPane, "Elemento: " + x,"Get",1);
            AreaVector.setText(PVector.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "La Pila no tiene Elementos","Estructura de Datos 1",1);
        }
    }//GEN-LAST:event_GetVectorActionPerformed

    private void GetBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetBitsActionPerformed
        if (!PBits.Vacia()) {
            int x = PBits.Get();
            JOptionPane.showMessageDialog(rootPane, "Elemento: " + x,"Get",1);
            AreaBits.setText(PBits.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "La Pila no tiene Elementos","Estructura de Datos 1",1);
        }
    }//GEN-LAST:event_GetBitsActionPerformed

    private void GetListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetListaActionPerformed
         if (!PLista.Vacia()) {
            int x = PLista.Get();
            JOptionPane.showMessageDialog(rootPane, "Elemento: " + x,"Get",1);
            AreaLista.setText(PLista.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "La Pila no tiene Elementos","Estructura de Datos 1",1);
        }
    }//GEN-LAST:event_GetListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilaFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaBits;
    private javax.swing.JTextArea AreaLista;
    private javax.swing.JTextArea AreaVector;
    private javax.swing.JTextField ETBits;
    private javax.swing.JTextField ETVector;
    private javax.swing.JTextField ElementoBits;
    private javax.swing.JTextField ElementoLista;
    private javax.swing.JTextField ElementoVector;
    private javax.swing.JButton GenerarBits;
    private javax.swing.JButton GetBits;
    private javax.swing.JButton GetLista;
    private javax.swing.JButton GetVector;
    private javax.swing.JTextField NBits;
    private javax.swing.JButton PopBits;
    private javax.swing.JButton PopLista;
    private javax.swing.JButton PopVector;
    private javax.swing.JButton PushBits;
    private javax.swing.JButton PushLista;
    private javax.swing.JButton PushVector;
    private javax.swing.JButton TamañoVector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
